#!/usr/bin/env python3
"""
AI Ethics Enforcement Core Library

This module provides comprehensive enforcement of AI attribution policies
across different systems and programming languages.

Author: Victor J. Quiñones (FutureTranz)
License: MIT
"""

import re
import json
import subprocess
import sys
import os
import argparse
from typing import Dict, List, Optional, Any
from dataclasses import dataclass
from enum import Enum


class AttributionViolation(Enum):
    """Types of AI attribution violations"""
    AI_CO_AUTHOR = "ai_co_author"
    AI_COMMIT_MESSAGE = "ai_commit_message"
    AI_CODE_COMMENT = "ai_code_comment"
    AI_GENERATED_MARKER = "ai_generated_marker"
    MISSING_HUMAN_ATTRIBUTION = "missing_human_attribution"
    AI_TOOL_ATTRIBUTION = "ai_tool_attribution"


@dataclass
class Violation:
    """Represents a policy violation"""
    violation_type: AttributionViolation
    line_number: Optional[int]
    content: str
    suggestion: str
    severity: str = "error"


class AIEthicsEnforcer:
    """
    Core AI Ethics Enforcement Engine

    Enforces maximum truth, zero bias, zero trust security,
    and least privileged access in AI systems.
    """

    # Prohibited AI attribution patterns
    AI_PATTERNS = {
        'co_authored_by': re.compile(
            r'Co-authored-by:\s*'
            r'(?:GitHub Copilot|Cursor|Codeium|Tabnine|Windsurf|Amazon Q|'
            r'Anthropic|Claude|GPT|AI|Assistant)',
            re.IGNORECASE
        ),
        'generated_by': re.compile(
            r'(?:Generated|Created|Written|Produced)\s+by\s+'
            r'(?:GitHub Copilot|Cursor|Codeium|Tabnine|Windsurf|Amazon Q|Anthropic|Claude|GPT|AI)',
            re.IGNORECASE
        ),
        'ai_assisted': re.compile(
            r'(?:AI-assisted|AI-generated|AI-written|AI-produced|Machine-generated)',
            re.IGNORECASE
        ),
        'tool_attribution': re.compile(
            r'(?:With help from|Assisted by|Powered by)\s+'
            r'(?:GitHub Copilot|Cursor|Codeium|Tabnine|Windsurf|Amazon Q|Anthropic)',
            re.IGNORECASE
        ),
        'commit_messages': re.compile(
            r'(?:AI|GPT|Copilot|Claude)\s+(?:generated|created|wrote|produced|helped)',
            re.IGNORECASE
        )
    }

    # Required human attribution patterns
    HUMAN_PATTERNS = {
        'human_author': re.compile(r'Author:\s*[A-Za-z\s]+(?:<[^>]+>)?'),
        'human_co_author': re.compile(
            r'Co-authored-by:\s*[A-Za-z\s]+(?:<[^>]+>)'
            r'(?!\s*(?:GitHub Copilot|Cursor|Codeium|Tabnine|Windsurf|Amazon Q|Anthropic))',
            re.IGNORECASE
        ),
        'signed_off': re.compile(r'Signed-off-by:\s*[A-Za-z\s]+(?:<[^>]+>)')
    }

    def __init__(self, config_path: Optional[str] = None):
        """Initialize the enforcer with optional configuration"""
        self.config = self._load_config(config_path)
        self.violations: List[Violation] = []

    def _load_config(self, config_path: Optional[str]) -> Dict[str, Any]:
        """Load configuration from file or use defaults"""
        default_config = {
            "maximum_truth": True,
            "zero_bias": True,
            "zero_trust": True,
            "least_privilege": True,
            "human_accountability": True,
            "attribution_protection": True,
            "allowed_human_patterns": [
                r"Author:\s*[A-Za-z\s]+(?:<[^>]+>)?",
                r"Co-authored-by:\s*[A-Za-z\s]+(?:<[^>]+>)"
                r"(?!\s*(?:GitHub Copilot|Cursor|Codeium|Tabnine|Windsurf|Amazon Q|Anthropic))"
            ],
            "prohibited_ai_patterns": [
                r"Co-authored-by:\s*"
                r"(?:GitHub Copilot|Cursor|Codeium|Tabnine|Windsurf|Amazon Q|Anthropic)",
                r"Generated by\s+"
                r"(?:GitHub Copilot|Cursor|Codeium|Tabnine|Windsurf|Amazon Q|Anthropic)",
                r"AI-(?:generated|assisted|written|produced)"
            ]
        }

        if config_path:
            try:
                with open(config_path, 'r', encoding='utf-8') as f:
                    user_config = json.load(f)
                default_config.update(user_config)
            except (FileNotFoundError, json.JSONDecodeError):
                pass

        return default_config

    def check_commit_message(self, message: str) -> List[Violation]:
        """Check commit message for AI attribution violations"""
        violations = []
        lines = message.split('\n')

        for i, line in enumerate(lines, 1):
            # Check for prohibited AI patterns
            for _, pattern in self.AI_PATTERNS.items():
                if pattern.search(line):
                    violations.append(Violation(
                        violation_type=AttributionViolation.AI_COMMIT_MESSAGE,
                        line_number=i,
                        content=line.strip(),
                        suggestion="Remove AI attribution from commit message. "
                        "Only human authors should be credited."
                    ))

            # Check for missing human attribution
            if not any(pattern.search(line) for pattern in self.HUMAN_PATTERNS.values()):
                if "Co-authored-by:" in line and not self._is_human_co_author(line):
                    violations.append(Violation(
                        violation_type=AttributionViolation.AI_CO_AUTHOR,
                        line_number=i,
                        content=line.strip(),
                        suggestion="Replace AI co-author with human co-author attribution."
                    ))

        return violations

    def check_code_content(self, content: str, filename: str = "") -> List[Violation]:
        """Check code content for AI attribution markers"""
        violations = []
        lines = content.split('\n')

        for i, line in enumerate(lines, 1):
            # Check for AI-generated markers in comments
            if self._is_comment_line(line, filename):
                for _, pattern in self.AI_PATTERNS.items():
                    if pattern.search(line):
                        violations.append(Violation(
                            violation_type=AttributionViolation.AI_CODE_COMMENT,
                            line_number=i,
                            content=line.strip(),
                            suggestion="Remove AI attribution from code comments. "
                            "AI tools are assistants, not authors."
                        ))

            # Check for AI-generated file headers
            if i <= 10:  # Check first 10 lines for headers
                if "generated by ai" in line.lower() or "ai generated" in line.lower():
                    violations.append(Violation(
                        violation_type=AttributionViolation.AI_GENERATED_MARKER,
                        line_number=i,
                        content=line.strip(),
                        suggestion="Remove AI generation markers from file headers."
                    ))

        return violations

    def check_git_commit(self, commit_hash: str = "HEAD") -> List[Violation]:
        """Check a git commit for policy violations"""
        violations = []

        try:
            # Get commit message
            result = subprocess.run(
                ["git", "log", "--format=%B", "-n", "1", commit_hash],
                capture_output=True, text=True, check=True
            )
            commit_message = result.stdout.strip()

            violations.extend(self.check_commit_message(commit_message))

            # Get commit author info
            result = subprocess.run(
                ["git", "log", "--format=%an <%ae>", "-n", "1", commit_hash],
                capture_output=True, text=True, check=True
            )
            author = result.stdout.strip()

            if self._is_ai_author(author):
                violations.append(Violation(
                    violation_type=AttributionViolation.AI_TOOL_ATTRIBUTION,
                    line_number=None,
                    content=f"Commit author: {author}",
                    suggestion="Commits must be authored by humans only. "
                    "AI tools cannot be commit authors."
                ))

        except subprocess.CalledProcessError:
            violations.append(Violation(
                violation_type=AttributionViolation.MISSING_HUMAN_ATTRIBUTION,
                line_number=None,
                content="Could not retrieve commit information",
                suggestion="Ensure commits are properly authored by humans."
            ))

        return violations

    def enforce_policy(self, target: str, target_type: str = "auto") -> Dict[str, Any]:
        """
        Main enforcement method

        Args:
            target: File path, commit hash, or content to check
            target_type: Type of target ("file", "commit", "content", "auto")

        Returns:
            Dict with compliance status and violations
        """
        self.violations = []

        if target_type == "auto":
            if target.startswith("commit:"):
                target_type = "commit"
                target = target[7:]
            elif self._is_file_path(target):
                target_type = "file"
            else:
                target_type = "content"

        if target_type == "file":
            try:
                with open(target, 'r', encoding='utf-8') as f:
                    content = f.read()
                self.violations.extend(self.check_code_content(content, target))
            except (FileNotFoundError, UnicodeDecodeError):
                self.violations.append(Violation(
                    violation_type=AttributionViolation.MISSING_HUMAN_ATTRIBUTION,
                    line_number=None,
                    content=f"Could not read file: {target}",
                    suggestion="Ensure file exists and is readable."
                ))

        elif target_type == "commit":
            self.violations.extend(self.check_git_commit(target))

        elif target_type == "content":
            # Check if content looks like a commit message
            # (short first line, blank line, then longer content)
            lines = target.split('\n')
            if (len(lines) >= 3 and
                    len(lines[0].strip()) < 100 and  # Short subject line
                    lines[1].strip() == '' and       # Blank line separator
                    any('Co-authored-by:' in line or 'Signed-off-by:' in line
                        for line in lines)):
                self.violations.extend(self.check_commit_message(target))
            else:
                self.violations.extend(self.check_code_content(target))

        return {
            "compliant": len(self.violations) == 0,
            "violations": [v.__dict__ for v in self.violations],
            "enforced_policies": {
                "maximum_truth": self.config["maximum_truth"],
                "zero_bias": self.config["zero_bias"],
                "zero_trust": self.config["zero_trust"],
                "least_privilege": self.config["least_privilege"],
                "human_accountability": self.config["human_accountability"],
                "attribution_protection": self.config["attribution_protection"]
            }
        }

    def _is_comment_line(self, line: str, filename: str) -> bool:
        """Check if a line is a comment in the given file type"""
        line = line.strip()
        if not line:
            return False

        # Language-specific comment patterns
        comment_patterns = {
            '.py': ['#', '"""', "'''"],
            '.js': ['//', '/*', '*'],
            '.ts': ['//', '/*', '*'],
            '.java': ['//', '/*', '*'],
            '.cpp': ['//', '/*'],
            '.c': ['//', '/*'],
            '.cs': ['//', '/*'],
            '.php': ['//', '#', '/*'],
            '.rb': ['#', '=begin'],
            '.go': ['//', '/*'],
            '.rs': ['//', '/*'],
            '.sh': ['#'],
            '.yml': ['#'],
            '.yaml': ['#'],
            '.json': [],  # JSON doesn't have comments
            '.xml': ['<!--'],
            '.html': ['<!--'],
            '.md': [],  # Markdown doesn't have code comments
        }

        # Get file extension
        ext = filename.split('.')[-1] if '.' in filename else ''
        ext = f'.{ext}'

        patterns = comment_patterns.get(ext, ['#', '//', '/*'])

        return any(line.startswith(pattern) for pattern in patterns)

    def _is_human_co_author(self, line: str) -> bool:
        """Check if co-author line represents a human"""
        # Must have email format and not contain AI tool names
        email_pattern = r'<[^>]+>'
        ai_tools = [
            'GitHub Copilot', 'Cursor', 'Codeium', 'Tabnine', 'Windsurf',
            'Amazon Q', 'Anthropic', 'Claude', 'GPT'
        ]

        has_email = bool(re.search(email_pattern, line))
        has_ai_tool = any(tool.lower() in line.lower() for tool in ai_tools)

        return has_email and not has_ai_tool

    def _is_ai_author(self, author: str) -> bool:
        """Check if author represents an AI tool"""
        ai_tools = [
            'GitHub Copilot', 'Cursor', 'Codeium', 'Tabnine', 'Windsurf',
            'Amazon Q', 'Anthropic', 'Claude', 'GPT', 'AI', 'Assistant'
        ]
        return any(tool.lower() in author.lower() for tool in ai_tools)

    def _is_file_path(self, target: str) -> bool:
        """Check if target is a file path"""
        return os.path.isfile(target)

    def get_policy_summary(self) -> Dict[str, Any]:
        """Get a summary of enforced policies"""
        return {
            "enforcer_version": "1.3.0",
            "author": "Victor J. Quiñones (FutureTranz)",
            "policies": {
                "maximum_truth": "Forces AI to provide accurate, verifiable information",
                "zero_bias": "Eliminates discriminatory patterns in AI outputs",
                "zero_trust": "Implements least privileged access and continuous verification",
                "least_privilege": "Minimal permissions for operations",
                "human_accountability": "All AI decisions require human oversight",
                "attribution_protection": "Prevents AI from claiming authorship of human work"
            },
            "supported_languages": [
                "Python", "JavaScript", "TypeScript", "Java", "C++", "C#",
                "PHP", "Ruby", "Go", "Rust", "Shell", "YAML", "JSON", "XML", "HTML"
            ]
        }


def main():
    """CLI interface for the AI Ethics Enforcer"""
    parser = argparse.ArgumentParser(
        description="AI Ethics Enforcement Tool - Enforce maximum truth, "
        "zero bias, zero trust security"
    )
    parser.add_argument(
        'target',
        help='File, commit hash, or content to check'
    )
    parser.add_argument(
        '--type', '-t',
        choices=['file', 'commit', 'content', 'auto'],
        default='auto',
        help='Type of target to check'
    )
    parser.add_argument(
        '--config', '-c',
        help='Path to configuration file'
    )
    parser.add_argument(
        '--format', '-f',
        choices=['json', 'text'],
        default='text',
        help='Output format'
    )

    args = parser.parse_args()

    # Handle stdin input
    target = args.target
    if target == "-":
        target = sys.stdin.read().strip()

    enforcer = AIEthicsEnforcer(args.config)
    result = enforcer.enforce_policy(target, args.type)

    if args.format == 'json':
        print(json.dumps(result, indent=2))
    else:
        print("🔍 AI Ethics Policy Check")
        print("=" * 50)

        if result['compliant']:
            print("✅ COMPLIANT - No policy violations found")
        else:
            print("❌ VIOLATIONS FOUND")
            for i, violation in enumerate(result['violations'], 1):
                print(f"\n{i}. {violation['violation_type'].value.upper()}")
                if violation['line_number']:
                    print(f"   Line {violation['line_number']}: {violation['content']}")
                else:
                    print(f"   {violation['content']}")
                print(f"   💡 {violation['suggestion']}")

        print(f"\n📋 Enforced Policies: "
              f"{', '.join(k for k, v in result['enforced_policies'].items() if v)}")

    sys.exit(0 if result['compliant'] else 1)


if __name__ == "__main__":
    main()
